language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - bundle exec rackup
  - sleep 3
script: bundle exec rspec spec
